In [123]:
import requests
import pandas as pd

In [125]:
url = "Scraped the data from https://davis.citizenrims.com/map"

# - Scraped data date ranges from 10/21/2020 to 2/28/2026
# - Filter for crimes only

In [129]:
params = {
    "agencyID": 914
}

In [131]:
# An authorization bearer token is required to scrape the data from the website

headers = {
    "User-Agent": "Your User Agent",
    "Authorization": "Authorization Bearer Token"
}

In [133]:
response = requests.get(url = url, headers=headers, params = params, timeout = 15)

In [134]:
response.raise_for_status()

In [135]:
# html_soup = BeautifulSoup(response.text, "html.parser")

In [136]:
# html_soup

In [137]:
# All Columns

'''
    {
        "id": 3953527,
        "caseNumber": "23-00779",
        "originalCaseNumber": 12300779, # Remove
        "agencyId": 914, # Remove
        "reportDate": "2023-02-18T00:00:00",
        "offenseCode1": "532(A) PC", # Remove
        "offenseCode2": "", # Remove
        "offenseCode3": "", # Remove
        "offenseCode4": "", # Remove
        "offenseCode5": "", # Remove
        "offenseCode6": "", # Remove
        "offenseDescription1": "Obtain money/etc by false pretenses [over $400] (F)",
        "offenseDescription2": "",
        "offenseDescription3": "",
        "offenseDescription4": "",
        "offenseDescription5": "",
        "offenseDescription6": "",
        "incidentNumber": 202302180066,
        "place": "SYCAMORE LANE APARTMENTS",
        "city": "Davis",
        "occurrence1Date": "2023-02-18T00:00:00",
        "occurrence1Time": 1200,
        "disposition": "",
        "beat": "1",
        "approvalDate": "2023-02-20T00:00:00", # Remove
        "approved": true, # Remove
        "xCoord": -121.761650085449,
        "yCoord": 38.5474700927734,
        "blockNumber": 600,
        "street": "SYCAMORE LN",
        "coordCheck": "Y",
        "uploadDate": "2025-11-14T12:20:01.737",
        "crimeType": "Fraud Offenses",
        "crimeClassification": "Felony",
        "titleBackgroundColor": "#752100", # Remove
        "iconUrl": "red\\PinNeedle.svg" # Remove
    }
'''

'\n    {\n        "id": 3953527,\n        "caseNumber": "23-00779",\n        "originalCaseNumber": 12300779, # Remove\n        "agencyId": 914, # Remove\n        "reportDate": "2023-02-18T00:00:00",\n        "offenseCode1": "532(A) PC", # Remove\n        "offenseCode2": "", # Remove\n        "offenseCode3": "", # Remove\n        "offenseCode4": "", # Remove\n        "offenseCode5": "", # Remove\n        "offenseCode6": "", # Remove\n        "offenseDescription1": "Obtain money/etc by false pretenses [over $400] (F)",\n        "offenseDescription2": "",\n        "offenseDescription3": "",\n        "offenseDescription4": "",\n        "offenseDescription5": "",\n        "offenseDescription6": "",\n        "incidentNumber": 202302180066,\n        "place": "SYCAMORE LANE APARTMENTS",\n        "city": "Davis",\n        "occurrence1Date": "2023-02-18T00:00:00",\n        "occurrence1Time": 1200,\n        "disposition": "",\n        "beat": "1",\n        "approvalDate": "2023-02-20T00:00:00", # Remove\n        "approved": true, # Remove\n        "xCoord": -121.761650085449,\n        "yCoord": 38.5474700927734,\n        "blockNumber": 600,\n        "street": "SYCAMORE LN",\n        "coordCheck": "Y",\n        "uploadDate": "2025-11-14T12:20:01.737",\n        "crimeType": "Fraud Offenses",\n        "crimeClassification": "Felony",\n        "titleBackgroundColor": "#752100", # Remove\n        "iconUrl": "red\\PinNeedle.svg" # Remove\n    }\n'

In [138]:
data = response.json()

In [139]:
df = pd.DataFrame(data)

In [140]:
df

,id,caseNumber,originalCaseNumber,agencyId,reportDate,offenseCode1,offenseCode2,offenseCode3,offenseCode4,offenseCode5,...,xCoord,yCoord,blockNumber,street,coordCheck,uploadDate,crimeType,crimeClassification,titleBackgroundColor,iconUrl
0,154571,21-01994,12101994,914,2021-05-17T00:00:00,288.3(A) PC,647.6(A)(1) PC,,,,...,-121.739891,38.557056,1200.0,DREXEL DR,Y,2025-03-25T09:00:17.477,All Other Offenses,Felony,#752100,red\PinNeedle.svg
1,164370,21-04672,12104672,914,2021-11-04T00:00:00,487(A) PC,182(A)(1) PC,11350(A) HS,978.5 PC,978.5 PC,...,-121.733101,38.560970,1400.0,E COVELL BL,Y,2024-10-02T21:00:02.427,Larceny/Theft,Felony,#752100,red\PinNeedle.svg
2,734070,21-04680,12104680,914,2021-11-05T00:00:00,261(A)(2) PC,11166 PC,,,,...,-121.750435,38.555664,300.0,W 14TH ST,Y,2025-09-05T10:25:02.48,Sex Offenses-Forcible,Felony,#752100,red\PinNeedle.svg
3,1767871,21-04689,12104689,914,2021-11-06T00:00:00,459 PC,,,,,...,-121.687393,38.553787,5100.0,CHILES RD,Y,2025-04-22T16:35:40.863,Burglary,Felony,#752100,red\PinNeedle.svg
4,158029,21-04769,12104769,914,2021-11-10T00:00:00,242 PC,484(A) PC,,,,...,-121.739601,38.546055,800.0,4TH ST,Y,2025-04-22T16:35:40.863,Assault,Misdemeanor,#752100,red\PinNeedle.svg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6613,4275994,26-00805,12600805,914,2026-02-27T00:00:00,978.5 PC,,,,,...,-121.738579,38.540657,1000.0,OLIVE DR,Y,2026-03-02T10:35:02.15,All Other Offenses,Misdemeanor,#752100,red\PinNeedle.svg
6614,4276270,26-00806,12600806,914,2026-02-27T00:00:00,647(F) PC,11364(A) HS,,,,...,-121.738152,38.544971,900.0,3RD ST,Y,2026-03-02T16:45:01.1,Disorderly Conduct,Misdemeanor,#752100,red\PinNeedle.svg
6615,4277739,26-00815,12600815,914,2026-02-28T00:00:00,11364(A) HS,11377(A) HS,,,,...,-121.734146,38.548828,500.0,L ST,Y,2026-03-03T10:30:02.487,Drug/Narcotic Offenses,Misdemeanor,#752100,red\PinNeedle.svg
6616,4276432,26-00820,12600820,914,2026-02-28T00:00:00,666.1(A)(1) PC,148(A)(1) PC,496(A) PC,647(F) PC,,...,-121.741417,38.544544,NaN,E ST/3RD ST,Y,2026-03-02T12:35:01.703,Larceny/Theft,Felony,#752100,red\PinNeedle.svg
6617,4275993,26-00824,12600824,914,2026-02-28T00:00:00,25400(A)(1) PC,33215 PC,25850(A) PC,23920(A) PC,32310(A) PC,...,-121.739998,38.543274,200.0,F ST,Y,2026-03-03T08:25:01.697,Weapon Law Violations,Felony,#752100,red\PinNeedle.svg

In [141]:
cols_to_drop = ['agencyId', 'offenseCode1', 'offenseCode2', 'offenseCode3', 'offenseCode4', 'offenseCode5', 'offenseCode6',
               'approvalDate', 'approved', 'originalCaseNumber', 'id', 'titleBackgroundColor', 'iconUrl']

In [142]:
df = df.drop(columns = cols_to_drop)

In [153]:
df

,caseNumber,reportDate,offenseDescription1,offenseDescription2,offenseDescription3,offenseDescription4,offenseDescription5,offenseDescription6,incidentNumber,place,...,disposition,beat,xCoord,yCoord,blockNumber,street,coordCheck,uploadDate,crimeType,crimeClassification
0,21-01994,2021-05-17T00:00:00,Contact minor with intent sex (F),Annoy/molest victim under 18 years of age - Di...,,,,,202105170050,HOLMES JUNIOR HIGH SCHOOL,...,C,2,-121.739891,38.557056,1200.0,DREXEL DR,Y,2025-03-25T09:00:17.477,All Other Offenses,Felony
1,21-04672,2021-11-04T00:00:00,Grand theft:money/labor/property - Shoplifting...,Conspiracy:commit crime (F),Possess narcotic controlled substance (M),Bench warrant/failure to appear on felony char...,Bench warrant/failure to appear on misdemeanor...,Shoplifting (M),202111040139,NUGGET MARKET,...,A,2,-121.733101,38.560970,1400.0,E COVELL BL,Y,2024-10-02T21:00:02.427,Larceny/Theft,Felony
2,21-04680,2021-11-05T00:00:00,Rape by force/fear/etc - Rape (F),Mandated Reporter/Child Abuse,,,,,202111050086,DAVIS HIGH SCHOOL,...,E,2,-121.750435,38.555664,300.0,W 14TH ST,Y,2025-09-05T10:25:02.48,Sex Offenses-Forcible,Felony
3,21-04689,2021-11-06T00:00:00,Burglary:second degree - Burglary/breaking and...,,,,,,202111060040,PKG HOLDINGS,...,,4,-121.687393,38.553787,5100.0,CHILES RD,Y,2025-04-22T16:35:40.863,Burglary,Felony
4,21-04769,2021-11-10T00:00:00,Battery on person - Simple (M),Theft of personal property - From motor vehicl...,,,,,202111100119,CORK IT AGAIN,...,A,2,-121.739601,38.546055,800.0,4TH ST,Y,2025-04-22T16:35:40.863,Assault,Misdemeanor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6613,26-00805,2026-02-27T00:00:00,Bench warrant/failure to appear on misdemeanor...,,,,,,202602270100,FIELD IBO LOC,...,A,4,-121.738579,38.540657,1000.0,OLIVE DR,Y,2026-03-02T10:35:02.15,All Other Offenses,Misdemeanor
6614,26-00806,2026-02-27T00:00:00,Disorderly conduct:alcohol (M),Possess unlawful paraphernalia (M),,,,,202602270116,BUSINESS COMPLEX BACK PLOT,...,A,2,-121.738152,38.544971,900.0,3RD ST,Y,2026-03-02T16:45:01.1,Disorderly Conduct,Misdemeanor
6615,26-00815,2026-02-28T00:00:00,Possess unlawful paraphernalia (M),Possess controlled substance (M),,,,,202602280079,RESPITE CENTER,...,A,2,-121.734146,38.548828,500.0,L ST,Y,2026-03-03T10:30:02.487,Drug/Narcotic Offenses,Misdemeanor
6616,26-00820,2026-02-28T00:00:00,Petty theft w/2 or more priors - All other lar...,Obstruct/resist/etc public/peace officer/emerg...,Receive/etc known stolen property (M),Disorderly conduct:alcohol (M),,,202602280112,ALLEY JWO CHIPOTLE,...,A,2,-121.741417,38.544544,NaN,E ST/3RD ST,Y,2026-03-02T12:35:01.703,Larceny/Theft,Felony
6617,26-00824,2026-02-28T00:00:00,Carry concealed weapon in vehicle (F),Mfg/import/etc short barreled rifle (F),Carry loaded firearm on/in person/vehicle:publ...,Poss/etc f/arm w/o id mrk (M),Mfg/sale/etc lrg cap mag (M),Felon/addict/possess/etc firearm (F),202602280184,ROOT OF HAPPINESS,...,A,2,-121.739998,38.543274,200.0,F ST,Y,2026-03-03T08:25:01.697,Weapon Law Violations,Felony

In [155]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6618 entries, 0 to 6617
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   caseNumber           6618 non-null   str
 1   reportDate           6618 non-null   str
 2   offenseDescription1  6618 non-null   str
 3   offenseDescription2  6618 non-null   str
 4   offenseDescription3  6618 non-null   str
 5   offenseDescription4  6618 non-null   str
 6   offenseDescription5  6618 non-null   str
 7   offenseDescription6  6618 non-null   str
 8   incidentNumber       6618 non-null   int64
 9   place                6618 non-null   str
 10  city                 6618 non-null   str
 11  occurrence1Date      6618 non-null   str
 12  occurrence1Time      6618 non-null   int64
 13  disposition          6618 non-null   str
 14  beat                 6618 non-null   str
 15  xCoord               6618 non-null   float64
 16  yCoord               6618 non-null   float64
 17  blockNumber          6093 non-null   float64
 18  street               6618 non-null   str
 19  coordCheck           6618 non-null   str
 20  uploadDate           6618 non-null   str
 21  crimeType            6618 non-null   str
 22  crimeClassification  6618 non-null   str
dtypes: float64(3), int64(2), str(18)
memory usage: 2.3 MB

In [157]:
df.isna().sum().sum()

np.int64(525)

In [159]:
df['blockNumber'] = df['blockNumber'].fillna(0.0).astype(int)

In [161]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6618 entries, 0 to 6617
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   caseNumber           6618 non-null   str
 1   reportDate           6618 non-null   str
 2   offenseDescription1  6618 non-null   str
 3   offenseDescription2  6618 non-null   str
 4   offenseDescription3  6618 non-null   str
 5   offenseDescription4  6618 non-null   str
 6   offenseDescription5  6618 non-null   str
 7   offenseDescription6  6618 non-null   str
 8   incidentNumber       6618 non-null   int64
 9   place                6618 non-null   str
 10  city                 6618 non-null   str
 11  occurrence1Date      6618 non-null   str
 12  occurrence1Time      6618 non-null   int64
 13  disposition          6618 non-null   str
 14  beat                 6618 non-null   str
 15  xCoord               6618 non-null   float64
 16  yCoord               6618 non-null   float64
 17  blockNumber          6618 non-null   int64
 18  street               6618 non-null   str
 19  coordCheck           6618 non-null   str
 20  uploadDate           6618 non-null   str
 21  crimeType            6618 non-null   str
 22  crimeClassification  6618 non-null   str
dtypes: float64(2), int64(3), str(18)
memory usage: 2.3 MB

In [163]:
df.to_csv('cleaned_crime_data(1).csv', index = False)